CXX = g++

all: ex1 ex2_1 ex2_2 ex3_1 ex3_2 ex4

ex1: ex1.cpp
	g++ -o ex1 ex1.cpp

ex2_1: ex2_1.cpp
	g++ -o ex2_1 ex2_1.cpp

ex2_2: ex2_2.cpp
	g++ -o ex2_2 ex2_2.cpp

ex3_1: ex3_1.cpp
	g++ -o ex3_1 ex3_1.cpp

ex3_2: ex3_2.cpp
	g++ -o ex3_2 ex3_2.cpp

ex4: ex4.cpp
	g++ -o ex4 ex4.cpp

clean:
	rm ex1 ex2_1 ex2_2 ex3_1 ex3_2 ex4
